#!/bin/bash
sudo "echo install usb-storage /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install bluetooth /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install net-pf-31 /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install freevxfs /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install appletalk /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install gfs2 /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install udf /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install ceph /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install appletalk /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo install vfat /bin/true >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist usb-storage >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist bluetooth >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist net-pf-31 >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist freevxfs >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist appletalk >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist gfs2 >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist udf >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist ceph >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist appletalk >> /etc/modprobe.d/DISASTIG.conf"
sudo "echo blacklist vfat >> /etc/modprobe.d/DISASTIG.conf"